
services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name : mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - "mariadb_data:/var/lib/mysql"

  adminer:
    image: adminer
    build: ./requirements/bonus/adminer/
    container_name : adminer
    ports:
      - "8080:8080"
    restart: always
    networks:
      - inception_network

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name : nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - "wordpress_data:/var/www/html"
    env_file:
      - .env


  wordpress:
    depends_on : 
      - mariadb 
    image: wordpress
    build: ./requirements/wordpress
    container_name : wordpress
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - "wordpress_data:/var/www/html"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mboulagh/data/mariadb_data

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mboulagh/data/wordpress_data

networks:
  inception_network:
    driver: bridge