
services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name : mariadb
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - "mariadb_data:/var/lib/mysql"

  # static_website:
  #   image: static_website
  #   build: ./requirements/bonus/static_website
  #   container_name : static_website
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - inception_network

  redis:
    image: redis
    build: ./requirements/bonus/redis
    container_name : redis
    restart: always
    networks:
      - inception_network

  # cadvisor:
  #   image: cadvisor
  #   build: ./requirements/bonus/cadvisor
  #   container_name : cadvisor
  #   restart: always
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro #for /sys/fs/cgroup
  #     - /var/lib/docker:/var/lib/docker:ro
  #   networks:
  #     - inception_network

  # adminer:
  #   image: adminer
  #   build: ./requirements/bonus/adminer/
  #   container_name : adminer
  #   ports:
  #     - "8080:8080"
  #   restart: always
  #   networks:
  #     - inception_network

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name : nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - "wordpress_data:/var/www/html"
    env_file:
      - .env


  wordpress:
    depends_on : 
      - mariadb 
    image: wordpress
    build: ./requirements/wordpress
    container_name : wordpress
    restart: always
    networks:
      - inception_network
    env_file:
      - .env
    volumes:
      - "wordpress_data:/var/www/html"

volumes:
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/mboulagh/data/mariadb_data

  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/mboulagh/data/wordpress_data

networks:
  inception_network:
    driver: bridge